import docker
import os, time
client = docker.from_env()
print(client.images.list())
container = client.containers.run(image='gcc', detach=True, tty=True)
print(container.short_id)
print(client.containers.list())
os.system("docker cp sol.cpp {}:/sol.cpp".format(container.short_id))
os.system("docker cp input.txt {}:/input.txt".format(container.short_id))
container.exec_run("g++ sol.cpp")
container.exec_run("touch output.txt")
time.sleep(2)
container.exec_run("chmod +x a.out")
output = container.exec_run(['sh', '-c', './a.out< input.txt > output.txt'])
print(output)
os.system("docker cp {}:/output.txt output.txt".format(container.short_id))
container.kill()
container.stop()
container.remove()
# container = client.containers.get('1b21a36204')
# print(container.exec_run(cmd="echo $PATH", stdout=True).output)