# Generated by Django 4.0.5 on 2022-07-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_submission_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.TextField(default='None'),
        ),
    ]
